export const Groceries = [
  {
    name: "Carrot",
    category: "Vegetable",
    varients: ["small", "medium", "large"],
    prices: [{ small: 1.99, medium: 2.99, large: 3.99 }],
    importance: "High",
    images: "/images/carrot.png",
    features: ["Rich in Vitamin A", "Good source of fiber"],
  },
  {
    name: "Apple",
    category: "Fruit",
    varients: ["small", "medium", "large"],
    prices: [{ small: 0.99, medium: 1.99, large: 2.99 }],
    importance: "Moderate",
    images: "/images/apple.png",
    features: ["Rich in antioxidants", "Contains dietary fiber"],
  },
  {
    name: "Vegan Red Tomato",
    category: "Vegetable",
    varients: ["small", "medium", "large"],
    prices: [{ small: 0.79, medium: 1.79, large: 2.79 }],
    importance: "Moderate",
    images: "/images/tomato.png",
    features: ["Rich in lycopene", "Contains Vitamin C"],
  },
  {
    name: "Calabrese Broccoli",
    category: "Vegetable",
    varients: ["small", "medium", "large"],
    prices: [{ small: 2.49, medium: 3.49, large: 4.49 }],
    importance: "High",
    images: "/images/broccoli.png",
    features: ["Rich in vitamins and minerals", "High in fiber"],
  },
  {
    name: "Fresh Banana Fruites",
    category: "Fruit",
    varients: ["small", "medium", "large"],
    prices: [{ small: 0.69, medium: 1.69, large: 2.69 }],
    importance: "Moderate",
    images: "/images/banana.png",
    features: ["Good source of potassium", "Rich in Vitamin C"],
  },
  {
    name: "Eggs",
    category: "Poultry",
    varients: ["small", "medium", "large"],
    prices: [{ small: 0.89, medium: 1.89, large: 2.89 }],
    importance: "Moderate",
    images: "/images/egg.png",
    features: ["Excellent source of protein", "Rich in essential vitamins"],
  },
  {
    name: "Mung Bean",
    category: "Vegetable",
    varients: ["small", "medium", "large"],
    prices: [{ small: 1.25, medium: 2.25, large: 3.25 }],
    importance: "Moderate",
    images: "/images/Mung bean.png",
    features: [
      "Rich in protein",
      "High in dietary fiber",
      "Good source of iron, magnesium, and potassium",
      "Contains B vitamins",
    ],
  },
  {
    name: "Lettuce",
    category: "Vegetable",
    varients: ["small", "medium", "large"],
    prices: [{ small: 1.49, medium: 2.49, large: 3.49 }],
    importance: "Low",
    images: "/images/lettuce.png",
    features: ["Good source of Vitamin K", "Low in calories"],
  },
  {
    name: "Beef",
    category: "Meat",
    varients: ["small", "medium", "large"],
    prices: [{ small: 8.99, medium: 9.99, large: 10.99 }],
    importance: "Moderate",
    images: "/images/beef.png",
    features: ["Rich in iron", "Good source of protein"],
  },
  {
    name: "Orange",
    category: "Fruit",
    varients: ["small", "medium", "large"],
    prices: [{ small: 0.79, medium: 1.79, large: 2.79 }],
    importance: "Moderate",
    images: "/images/orange.png",
    features: ["High in Vitamin C", "Contains dietary fiber"],
  },
  {
    name: "Spinach",
    category: "Vegetable",
    varients: ["small", "medium", "large"],
    prices: [{ small: 1.29, medium: 2.29, large: 3.29 }],
    importance: "High",
    images: "/images/spinach.png",
    features: ["Rich in iron", "Good source of vitamins"],
  },
  {
    name: "Organic Almonds",
    category: "Nuts",
    varients: ["small", "medium", "large"],
    prices: [{ small: 5.99, medium: 6.99, large: 7.99 }],
    importance: "High",
    images: "/images/almond.png",
    features: ["Good source of healthy fats", "High in Vitamin E"],
  },
  {
    name: "Strawberry",
    category: "Fruit",
    varients: ["small", "medium", "large"],
    prices: [{ small: 1.49, medium: 2.49, large: 3.49 }],
    importance: "Moderate",
    images: "/images/strawberry.png",
    features: ["Rich in antioxidants", "Good source of Vitamin C"],
  },
  {
    name: "Cabbage",
    category: "Vegetable",
    varients: ["small", "medium", "large"],
    prices: [{ small: 1.19, medium: 2.19, large: 3.19 }],
    importance: "Moderate",
    images: "/images/cabbage.png",
    features: ["High in fiber", "Rich in Vitamin C"],
  },
  {
    name: "Fresh Corn",
    category: "Legume",
    varients: ["small", "medium", "large"],
    prices: [{ small: 0.14, medium: 1.14, large: 2.14 }],
    importance: "Moderate",
    images: "/images/corn.png",
    features: [
      "Good source of carbohydrates",
      "Contains dietary fiber",
      "Rich in vitamin C",
      "Provides thiamine and folate",
    ],
  },
  {
    name: "Pineapple",
    category: "Fruit",
    varients: ["small", "medium", "large"],
    prices: [{ small: 2.99, medium: 3.99, large: 4.99 }],
    importance: "Moderate",
    images: "/images/pineapple.png",
    features: ["High in Vitamin C", "Contains bromelain enzyme"],
  },
];

export default Groceries;
